export const aiWorkspaceLabels = {
  tr: {
    period: 'Sorgu dönemi', auto: 'Sorudan belirle', today: 'Bugün', month: 'Bu ay', previousMonth: 'Geçen ay', custom: 'Özel tarih', from: 'Başlangıç tarihi', to: 'Bitiş tarihi', periodError: 'Geçerli başlangıç ve bitiş tarihlerini girin; başlangıç bitişten sonra olamaz.', periodHint: 'Seçtiğiniz tarihler sorguya eklenir. Yanıtta kullanılan dönemi kontrol edin. Saat dilimi: Africa/Algiers.', answerPeriod: 'Yanıt dönemi',
    orders: 'Siparişlerim üzerinden sor', ordersHint: 'Siparişi seç, sorunu yaz; numarası komuta eklensin.', load: 'Siparişleri getir', loading: 'Siparişler yükleniyor…', error: 'Siparişler alınamadı. Tekrar deneyin.', empty: 'Eşleşen sipariş bulunamadı.', search: 'Sipariş no, müşteri veya ürün ara', choose: 'Sipariş seç', status: 'Bu siparişin durumu nedir?', delivery: 'Bu siparişte teslim edilen ve kalan miktar nedir?', payment: 'Bu siparişte tahsil edilen ve kalan tutar nedir?', reference: 'Sipariş', source: 'Kaynak', records: 'Kullanılan kayıt', keyboard: 'Enter ile gönder · Shift + Enter ile yeni satır', followUp: 'Konuşmaya devam et', detail: 'Daha ayrıntılı açıkla.', next: 'Bu verilere göre sıradaki adım ne olmalı?', draftReady: 'Taslak hazır. Kontrol edip gönderin.', intro: 'İşletmenizin günlük işleri, tek konuşmada.', queryHint: 'Örneğin: Bekleyen siparişleri teslim tarihine göre sırala', examples: 'Bir soruyla başlayın', loaded: 'Sipariş kayıtları · Alınma zamanı', history: 'Önceki yanıtlar',
  },
  en: {
    period: 'Query period', auto: 'Use question dates', today: 'Today', month: 'This month', previousMonth: 'Last month', custom: 'Custom dates', from: 'Start date', to: 'End date', periodError: 'Enter valid start and end dates; start must not be after end.', periodHint: 'Selected dates are included in the query. Check the period used in the answer. Time zone: Africa/Algiers.', answerPeriod: 'Answer period',
    orders: 'Ask about my orders', ordersHint: 'Choose an order to include its number in your question.', load: 'Load orders', loading: 'Loading orders…', error: 'Could not load orders. Try again.', empty: 'No matching orders.', search: 'Search order number, customer or product', choose: 'Select order', status: 'What is the status of this order?', delivery: 'What quantities have been delivered and remain on this order?', payment: 'What amounts have been collected and remain on this order?', reference: 'Order', source: 'Source', records: 'Records used', keyboard: 'Enter to send · Shift + Enter for a new line', followUp: 'Continue the conversation', detail: 'Explain in more detail.', next: 'What should be the next step based on this data?', draftReady: 'Draft ready. Review and send.', intro: 'Your daily business, in one conversation.', queryHint: 'For example: Sort pending orders by delivery date', examples: 'Start with a question', loaded: 'Order records · Retrieved', history: 'Previous answers',
  },
  fr: {
    period: 'Période de recherche', auto: 'Selon la question', today: 'Aujourd’hui', month: 'Ce mois', previousMonth: 'Mois dernier', custom: 'Dates personnalisées', from: 'Date de début', to: 'Date de fin', periodError: 'Saisissez des dates valides ; le début ne doit pas dépasser la fin.', periodHint: 'Les dates choisies sont ajoutées à la requête. Vérifiez la période de la réponse. Fuseau : Africa/Algiers.', answerPeriod: 'Période de la réponse',
    orders: 'Interroger mes commandes', ordersHint: 'Choisissez une commande pour ajouter son numéro à la question.', load: 'Charger les commandes', loading: 'Chargement…', error: 'Chargement impossible. Réessayez.', empty: 'Aucune commande correspondante.', search: 'Rechercher numéro, client ou produit', choose: 'Choisir une commande', status: 'Quel est le statut de cette commande ?', delivery: 'Quelles quantités sont livrées et restantes sur cette commande ?', payment: 'Quels montants sont encaissés et restants sur cette commande ?', reference: 'Commande', source: 'Source', records: 'Enregistrements utilisés', keyboard: 'Entrée pour envoyer · Maj + Entrée pour une nouvelle ligne', followUp: 'Continuer la conversation', detail: 'Explique plus en détail.', next: 'Quelle est la prochaine étape selon ces données ?', draftReady: 'Brouillon prêt. Vérifiez puis envoyez.', intro: 'Votre activité quotidienne, dans une conversation.', queryHint: 'Exemple : Trier les commandes en attente par date de livraison', examples: 'Commencez par une question', loaded: 'Commandes · Récupérées le', history: 'Réponses précédentes',
  },
  ar: {
    period: 'فترة الاستعلام', auto: 'حسب السؤال', today: 'اليوم', month: 'هذا الشهر', previousMonth: 'الشهر الماضي', custom: 'تواريخ مخصصة', from: 'تاريخ البداية', to: 'تاريخ النهاية', periodError: 'أدخل تاريخين صالحين؛ يجب ألا تتجاوز البداية النهاية.', periodHint: 'تضاف التواريخ المختارة إلى الاستعلام. راجع الفترة المستخدمة في الإجابة. المنطقة الزمنية: Africa/Algiers.', answerPeriod: 'فترة الإجابة',
    orders: 'اسأل عن طلباتي', ordersHint: 'اختر طلباً لإضافة رقمه إلى سؤالك.', load: 'تحميل الطلبات', loading: 'جار تحميل الطلبات…', error: 'تعذر تحميل الطلبات. أعد المحاولة.', empty: 'لا توجد طلبات مطابقة.', search: 'ابحث برقم الطلب أو العميل أو المنتج', choose: 'اختر الطلب', status: 'ما حالة هذا الطلب؟', delivery: 'ما الكمية المسلمة والمتبقية في هذا الطلب؟', payment: 'ما المبلغ المحصل والمتبقي في هذا الطلب؟', reference: 'الطلب', source: 'المصدر', records: 'السجلات المستخدمة', keyboard: 'Enter للإرسال · Shift + Enter لسطر جديد', followUp: 'تابع المحادثة', detail: 'اشرح بمزيد من التفاصيل.', next: 'ما الخطوة التالية بناء على هذه البيانات؟', draftReady: 'المسودة جاهزة. راجعها وأرسلها.', intro: 'أعمالك اليومية في محادثة واحدة.', queryHint: 'مثال: رتب الطلبات المعلقة حسب تاريخ التسليم', examples: 'ابدأ بسؤال', loaded: 'سجلات الطلبات · وقت التحميل', history: 'الإجابات السابقة',
  },
}


