export const cashFlowTranslations = {
  tr: {
    'cashflow.loadError': 'Nakit akışı alınamadı.', 'cashflow.noData': 'Nakit akışı verisi bulunamadı.', 'cashflow.loading': 'Nakit akışı yükleniyor…', 'cashflow.title': 'Nakit Akışı', 'cashflow.subtitle': 'Kasa hareketi + tedarikçi vadeleri · sipariş cirosu nakit değildir',
    'cashflow.currentCash': 'Mevcut Nakit', 'cashflow.collections30d': 'Son 30 Gün Tahsilat', 'cashflow.outflow30d': 'Son 30 Gün Gider/Ödeme', 'cashflow.upcoming7d': 'Önümüzdeki 7 Gün Ödenecek', 'cashflow.overdueDebt': 'Vadesi Geçmiş Borç', 'cashflow.netChange': 'Net Nakit Değişimi', 'cashflow.forecast': '7 günlük likidite tahmini',
    'cashflow.forecastWithCollection': 'Mevcut nakit {cash} − bilinen ödemeler {payments} + doğrulanmış tahsilat {collections}', 'cashflow.forecastWithoutCollection': 'Mevcut nakit {cash} − bilinen ödemeler {payments} · doğrulanmamış tahsilat dahil edilmedi',
    'cashflow.risk.SAFE': 'Güvenli', 'cashflow.risk.WATCH': 'İzle', 'cashflow.risk.RISK': 'Risk', 'cashflow.actual30d': '30 günlük gerçek nakit', 'cashflow.chartLabel': '30 günlük nakit grafiği', 'cashflow.inflow': 'Para girişi', 'cashflow.outflow': 'Para çıkışı', 'cashflow.net': 'Net değişim',
    'cashflow.calendar7d': '7 günlük ödeme takvimi', 'cashflow.noUpcoming': 'Önümüzdeki 7 günde vadesi gelen tedarikçi ödemesi yok.', 'cashflow.supplierDebt': 'Tedarikçi borcu', 'cashflow.expected': 'Beklenen tahsilat', 'cashflow.date': 'Tarih', 'cashflow.customer': 'Müşteri', 'cashflow.amount': 'Tutar', 'cashflow.noticeUnavailable': 'Doğrulanmış beklenen tahsilat verisi bulunmuyor.',
  },
  fr: {
    'cashflow.loadError': 'Impossible de charger le flux de trésorerie.', 'cashflow.noData': 'Aucune donnée de trésorerie disponible.', 'cashflow.loading': 'Chargement du flux de trésorerie…', 'cashflow.title': 'Flux de trésorerie', 'cashflow.subtitle': 'Mouvements de caisse + échéances fournisseurs · le chiffre d’affaires n’est pas du cash',
    'cashflow.currentCash': 'Trésorerie actuelle', 'cashflow.collections30d': 'Encaissements sur 30 jours', 'cashflow.outflow30d': 'Dépenses/paiements sur 30 jours', 'cashflow.upcoming7d': 'À payer dans les 7 jours', 'cashflow.overdueDebt': 'Dette en retard', 'cashflow.netChange': 'Variation nette de trésorerie', 'cashflow.forecast': 'Prévision de liquidité à 7 jours',
    'cashflow.forecastWithCollection': 'Trésorerie {cash} − paiements connus {payments} + encaissements vérifiés {collections}', 'cashflow.forecastWithoutCollection': 'Trésorerie {cash} − paiements connus {payments} · encaissements non vérifiés exclus',
    'cashflow.risk.SAFE': 'Sûre', 'cashflow.risk.WATCH': 'À surveiller', 'cashflow.risk.RISK': 'Risque', 'cashflow.actual30d': 'Trésorerie réelle sur 30 jours', 'cashflow.chartLabel': 'Graphique de trésorerie sur 30 jours', 'cashflow.inflow': 'Entrées', 'cashflow.outflow': 'Sorties', 'cashflow.net': 'Variation nette',
    'cashflow.calendar7d': 'Calendrier de paiement sur 7 jours', 'cashflow.noUpcoming': 'Aucun paiement fournisseur n’arrive à échéance dans les 7 jours.', 'cashflow.supplierDebt': 'Dette fournisseur', 'cashflow.expected': 'Encaissements attendus', 'cashflow.date': 'Date', 'cashflow.customer': 'Client', 'cashflow.amount': 'Montant', 'cashflow.noticeUnavailable': 'Aucune donnée vérifiée sur les encaissements attendus.',
  },
  en: {
    'cashflow.loadError': 'Cash flow could not be loaded.', 'cashflow.noData': 'Cash flow data is unavailable.', 'cashflow.loading': 'Loading cash flow…', 'cashflow.title': 'Cash flow', 'cashflow.subtitle': 'Cash movements + supplier due dates · order revenue is not cash',
    'cashflow.currentCash': 'Current cash', 'cashflow.collections30d': 'Collections in last 30 days', 'cashflow.outflow30d': 'Expenses/payments in last 30 days', 'cashflow.upcoming7d': 'Due in next 7 days', 'cashflow.overdueDebt': 'Overdue debt', 'cashflow.netChange': 'Net cash change', 'cashflow.forecast': '7-day liquidity forecast',
    'cashflow.forecastWithCollection': 'Current cash {cash} − known payments {payments} + verified collections {collections}', 'cashflow.forecastWithoutCollection': 'Current cash {cash} − known payments {payments} · unverified collections excluded',
    'cashflow.risk.SAFE': 'Safe', 'cashflow.risk.WATCH': 'Watch', 'cashflow.risk.RISK': 'Risk', 'cashflow.actual30d': 'Actual cash over 30 days', 'cashflow.chartLabel': '30-day cash chart', 'cashflow.inflow': 'Cash in', 'cashflow.outflow': 'Cash out', 'cashflow.net': 'Net change',
    'cashflow.calendar7d': '7-day payment calendar', 'cashflow.noUpcoming': 'No supplier payments are due in the next 7 days.', 'cashflow.supplierDebt': 'Supplier debt', 'cashflow.expected': 'Expected collections', 'cashflow.date': 'Date', 'cashflow.customer': 'Customer', 'cashflow.amount': 'Amount', 'cashflow.noticeUnavailable': 'No verified expected collection data is available.',
  },
} as const
