export const financeDebtTranslations = {
  tr: {
    'debt.loadError': 'Tedarikçi borçları alınamadı.', 'debt.detailError': 'Borç detayı alınamadı.', 'debt.paymentError': 'Ödeme kaydedilemedi.',
    'debt.title': 'Borçlarım', 'debt.subtitle': 'Şirketin tedarikçilere borcu · müşteri alacağı değil', 'debt.totalOpen': 'Toplam Açık Borç', 'debt.dueWeek': 'Bu Hafta Ödenecek', 'debt.overdueKpi': 'Vadesi Geçmiş', 'debt.paidMonth': 'Bu Ay Ödenen',
    'debt.filter.ALL': 'Tümü', 'debt.status.OPEN': 'Açık', 'debt.status.PARTIALLY_PAID': 'Kısmi ödenmiş', 'debt.status.PAID': 'Ödenmiş', 'debt.status.DUE_SOON': 'Vadesi yaklaşıyor', 'debt.status.OVERDUE': 'Vadesi geçmiş',
    'debt.supplier': 'Tedarikçi', 'debt.searchName': 'İsim ara', 'debt.dueFrom': 'Vade başlangıç', 'debt.dueTo': 'Vade bitiş', 'debt.minRemaining': 'Min kalan', 'debt.maxRemaining': 'Max kalan', 'debt.filter': 'Filtrele',
    'debt.creditorSupplier': 'Alacaklı / Tedarikçi', 'debt.type': 'Borç Türü', 'debt.total': 'Toplam Borç', 'debt.paid': 'Ödenen', 'debt.remaining': 'Kalan', 'debt.due': 'Vade', 'debt.status': 'Durum', 'debt.lastTransaction': 'Son İşlem', 'debt.action': 'İşlem', 'debt.pay': 'Ödeme Yap', 'debt.empty': 'Kayıtlı tedarikçi borcu yok. Borç yalnızca mal kabul onayında oluşur.',
    'debt.detail': 'Borç detayı', 'debt.totalPurchases': 'Toplam alış', 'debt.dueValue': 'vade {date}', 'debt.movements': 'Hareketler', 'debt.date': 'Tarih', 'debt.transaction': 'İşlem', 'debt.document': 'Belge', 'debt.debit': 'Borç', 'debt.payment': 'Ödeme', 'debt.noMovements': 'Hareket yok.', 'debt.paymentTitle': 'Ödeme · {name}', 'debt.amount': 'Tutar ({currency})', 'debt.description': 'Açıklama', 'debt.cashAccount': 'Kasa hesabı', 'debt.defaultAccount': 'Varsayılan (ANA-KASA)', 'debt.saving': 'Kaydediliyor…', 'debt.submitPayment': 'Öde', 'debt.invalidAmount': 'Geçerli bir tutar girin.', 'debt.paymentDescription': 'Tedarikçi ödemesi · {name}',
  },
  fr: {
    'debt.loadError': 'Impossible de charger les dettes fournisseurs.', 'debt.detailError': 'Impossible de charger le détail de la dette.', 'debt.paymentError': 'Impossible d’enregistrer le paiement.',
    'debt.title': 'Dettes', 'debt.subtitle': 'Dettes de l’entreprise envers les fournisseurs · hors créances clients', 'debt.totalOpen': 'Dette ouverte totale', 'debt.dueWeek': 'À payer cette semaine', 'debt.overdueKpi': 'En retard', 'debt.paidMonth': 'Payé ce mois-ci',
    'debt.filter.ALL': 'Tous', 'debt.status.OPEN': 'Ouverte', 'debt.status.PARTIALLY_PAID': 'Partiellement payée', 'debt.status.PAID': 'Payée', 'debt.status.DUE_SOON': 'Échéance proche', 'debt.status.OVERDUE': 'En retard',
    'debt.supplier': 'Fournisseur', 'debt.searchName': 'Rechercher un nom', 'debt.dueFrom': 'Échéance début', 'debt.dueTo': 'Échéance fin', 'debt.minRemaining': 'Reste min.', 'debt.maxRemaining': 'Reste max.', 'debt.filter': 'Filtrer',
    'debt.creditorSupplier': 'Créancier / Fournisseur', 'debt.type': 'Type de dette', 'debt.total': 'Dette totale', 'debt.paid': 'Payé', 'debt.remaining': 'Restant', 'debt.due': 'Échéance', 'debt.status': 'Statut', 'debt.lastTransaction': 'Dernière opération', 'debt.action': 'Action', 'debt.pay': 'Payer', 'debt.empty': 'Aucune dette fournisseur enregistrée. Une dette est créée uniquement à la validation de la réception.',
    'debt.detail': 'Détail de la dette', 'debt.totalPurchases': 'Total achats', 'debt.dueValue': 'échéance {date}', 'debt.movements': 'Mouvements', 'debt.date': 'Date', 'debt.transaction': 'Opération', 'debt.document': 'Document', 'debt.debit': 'Dette', 'debt.payment': 'Paiement', 'debt.noMovements': 'Aucun mouvement.', 'debt.paymentTitle': 'Paiement · {name}', 'debt.amount': 'Montant ({currency})', 'debt.description': 'Description', 'debt.cashAccount': 'Compte de caisse', 'debt.defaultAccount': 'Par défaut (ANA-KASA)', 'debt.saving': 'Enregistrement…', 'debt.submitPayment': 'Payer', 'debt.invalidAmount': 'Saisissez un montant valide.', 'debt.paymentDescription': 'Paiement fournisseur · {name}',
  },
  en: {
    'debt.loadError': 'Supplier debts could not be loaded.', 'debt.detailError': 'Debt details could not be loaded.', 'debt.paymentError': 'The payment could not be saved.',
    'debt.title': 'Payables', 'debt.subtitle': 'Company debt to suppliers · excludes customer receivables', 'debt.totalOpen': 'Total open debt', 'debt.dueWeek': 'Due this week', 'debt.overdueKpi': 'Overdue', 'debt.paidMonth': 'Paid this month',
    'debt.filter.ALL': 'All', 'debt.status.OPEN': 'Open', 'debt.status.PARTIALLY_PAID': 'Partially paid', 'debt.status.PAID': 'Paid', 'debt.status.DUE_SOON': 'Due soon', 'debt.status.OVERDUE': 'Overdue',
    'debt.supplier': 'Supplier', 'debt.searchName': 'Search name', 'debt.dueFrom': 'Due from', 'debt.dueTo': 'Due to', 'debt.minRemaining': 'Min remaining', 'debt.maxRemaining': 'Max remaining', 'debt.filter': 'Filter',
    'debt.creditorSupplier': 'Creditor / Supplier', 'debt.type': 'Debt type', 'debt.total': 'Total debt', 'debt.paid': 'Paid', 'debt.remaining': 'Remaining', 'debt.due': 'Due date', 'debt.status': 'Status', 'debt.lastTransaction': 'Last transaction', 'debt.action': 'Action', 'debt.pay': 'Make payment', 'debt.empty': 'No supplier debt is recorded. Debt is created only when a goods receipt is approved.',
    'debt.detail': 'Debt details', 'debt.totalPurchases': 'Total purchases', 'debt.dueValue': 'due {date}', 'debt.movements': 'Movements', 'debt.date': 'Date', 'debt.transaction': 'Transaction', 'debt.document': 'Document', 'debt.debit': 'Debt', 'debt.payment': 'Payment', 'debt.noMovements': 'No movements.', 'debt.paymentTitle': 'Payment · {name}', 'debt.amount': 'Amount ({currency})', 'debt.description': 'Description', 'debt.cashAccount': 'Cash account', 'debt.defaultAccount': 'Default (ANA-KASA)', 'debt.saving': 'Saving…', 'debt.submitPayment': 'Pay', 'debt.invalidAmount': 'Enter a valid amount.', 'debt.paymentDescription': 'Supplier payment · {name}',
  },
} as const
