export const userManagementTranslations = {
  tr: {
    'userMgmt.adminOnly': 'Bu sayfaya yalnızca yöneticiler erişebilir.',
    'userMgmt.loadError': 'Kullanıcı hesapları alınamadı.', 'userMgmt.saveError': 'Kullanıcı kaydedilemedi.', 'userMgmt.total': 'Toplam Kullanıcı', 'userMgmt.activeCount': 'Aktif Hesap', 'userMgmt.adminCount': 'Yönetici', 'userMgmt.viewerCount': 'Salt Okunur', 'userMgmt.title': 'Kullanıcı Yönetimi', 'userMgmt.subtitle': 'VEXOR’a giriş yapabilen hesaplar ve yetkileri', 'userMgmt.search': 'Ad, e-posta veya rol ara…', 'userMgmt.add': 'Kullanıcı Ekle', 'userMgmt.name': 'Ad', 'userMgmt.email': 'E-posta', 'userMgmt.role': 'Yetki Rolü', 'userMgmt.status': 'Durum', 'userMgmt.created': 'Oluşturulma', 'userMgmt.action': 'İşlem', 'userMgmt.empty': 'Henüz kullanıcı hesabı bulunmuyor.', 'userMgmt.editTitle': 'Kullanıcıyı Düzenle', 'userMgmt.createTitle': 'Yeni Kullanıcı Hesabı', 'userMgmt.fullName': 'Ad soyad', 'userMgmt.activeUser': 'Aktif kullanıcı', 'userMgmt.saving': 'Kaydediliyor…', 'userMgmt.saveChanges': 'Değişiklikleri Kaydet', 'userMgmt.create': 'Kullanıcı Oluştur',
    'userMgmt.role.VIEWER': 'Görüntüleyici — yalnızca okuma', 'userMgmt.role.MEMBER': 'Operasyon kullanıcısı', 'userMgmt.role.ACCOUNTING_OPERATOR': 'Muhasebe Operatörü — finans ve cari', 'userMgmt.role.ACCOUNTING_OPERATIONS': 'Muhasebe & Operasyon — günlük operasyon ve finans', 'userMgmt.role.PRODUCTION_MANAGER': 'Üretim Müdürü — üretim ve stok', 'userMgmt.role.ADMIN': 'Yönetici — tam yetki', 'userMgmt.role.OWNER': 'Şirket Sahibi — tam şirket yetkisi',
  },
  fr: {
    'userMgmt.adminOnly': 'Seuls les administrateurs peuvent accéder à cette page.',
    'userMgmt.loadError': 'Impossible de charger les comptes utilisateurs.', 'userMgmt.saveError': 'Impossible d’enregistrer l’utilisateur.', 'userMgmt.total': 'Total utilisateurs', 'userMgmt.activeCount': 'Comptes actifs', 'userMgmt.adminCount': 'Administrateurs', 'userMgmt.viewerCount': 'Lecture seule', 'userMgmt.title': 'Gestion des utilisateurs', 'userMgmt.subtitle': 'Comptes autorisés à se connecter à VEXOR et leurs permissions', 'userMgmt.search': 'Rechercher par nom, e-mail ou rôle…', 'userMgmt.add': 'Ajouter un utilisateur', 'userMgmt.name': 'Nom', 'userMgmt.email': 'E-mail', 'userMgmt.role': 'Rôle', 'userMgmt.status': 'Statut', 'userMgmt.created': 'Créé le', 'userMgmt.action': 'Action', 'userMgmt.empty': 'Aucun compte utilisateur.', 'userMgmt.editTitle': 'Modifier l’utilisateur', 'userMgmt.createTitle': 'Nouveau compte utilisateur', 'userMgmt.fullName': 'Nom complet', 'userMgmt.activeUser': 'Utilisateur actif', 'userMgmt.saving': 'Enregistrement…', 'userMgmt.saveChanges': 'Enregistrer les modifications', 'userMgmt.create': 'Créer l’utilisateur',
    'userMgmt.role.VIEWER': 'Lecteur — lecture seule', 'userMgmt.role.MEMBER': 'Utilisateur opérationnel', 'userMgmt.role.ACCOUNTING_OPERATOR': 'Opérateur comptable — finances et comptes', 'userMgmt.role.ACCOUNTING_OPERATIONS': 'Comptabilité et opérations — opérations quotidiennes et finances', 'userMgmt.role.PRODUCTION_MANAGER': 'Responsable production — production et stock', 'userMgmt.role.ADMIN': 'Administrateur — accès complet', 'userMgmt.role.OWNER': 'Propriétaire — accès complet à l’entreprise',
  },
  en: {
    'userMgmt.adminOnly': 'Only administrators can access this page.',
    'userMgmt.loadError': 'User accounts could not be loaded.', 'userMgmt.saveError': 'The user could not be saved.', 'userMgmt.total': 'Total users', 'userMgmt.activeCount': 'Active accounts', 'userMgmt.adminCount': 'Administrators', 'userMgmt.viewerCount': 'Read only', 'userMgmt.title': 'User management', 'userMgmt.subtitle': 'Accounts that can sign in to VEXOR and their permissions', 'userMgmt.search': 'Search name, email, or role…', 'userMgmt.add': 'Add user', 'userMgmt.name': 'Name', 'userMgmt.email': 'Email', 'userMgmt.role': 'Permission role', 'userMgmt.status': 'Status', 'userMgmt.created': 'Created', 'userMgmt.action': 'Action', 'userMgmt.empty': 'No user accounts found.', 'userMgmt.editTitle': 'Edit user', 'userMgmt.createTitle': 'New user account', 'userMgmt.fullName': 'Full name', 'userMgmt.activeUser': 'Active user', 'userMgmt.saving': 'Saving…', 'userMgmt.saveChanges': 'Save changes', 'userMgmt.create': 'Create user',
    'userMgmt.role.VIEWER': 'Viewer — read only', 'userMgmt.role.MEMBER': 'Operations user', 'userMgmt.role.ACCOUNTING_OPERATOR': 'Accounting operator — finance and ledgers', 'userMgmt.role.ACCOUNTING_OPERATIONS': 'Accounting and operations — daily operations and finance', 'userMgmt.role.PRODUCTION_MANAGER': 'Production manager — production and stock', 'userMgmt.role.ADMIN': 'Administrator — full access', 'userMgmt.role.OWNER': 'Company owner — full company access',
  },
} as const
