export const workforceTranslations = {
  tr: {
    'workforce.loadError': 'Çalışanlar alınamadı.', 'workforce.planLoadError': 'Çalışma planı alınamadı.', 'workforce.planSaveError': 'Plan kaydedilemedi.', 'workforce.tab.team': 'Personeller', 'workforce.tab.daily': 'Günlük Çalışma', 'workforce.tab.plan': 'Vardiya Planı', 'workforce.tab.leave': 'İzin / Devamsızlık', 'workforce.tab.weekly': 'Haftalık Plan', 'workforce.total': 'Toplam Personel', 'workforce.active': 'Aktif', 'workforce.salaryTotal': 'Aylık Maaş Toplamı', 'workforce.reviewCount': 'İnceleme Gereken', 'workforce.title': 'TRIKOMEX Çalışanları', 'workforce.report': 'Personel Raporu', 'workforce.search': 'Personel ara…', 'workforce.name': 'Ad', 'workforce.code': 'Personel Kodu', 'workforce.noCode': 'KOD YOK', 'workforce.salary': 'Aylık Maaş', 'workforce.shiftToday': 'Bugünkü Vardiya', 'workforce.statusToday': 'Bugünkü Durum', 'workforce.reviewRequired': 'İnceleme gerekiyor', 'workforce.notPlanned': 'Planlanmadı', 'workforce.empty': 'Henüz personel bulunmuyor.',
    'workforce.planTitle': 'Personel Çalışma Planı', 'workforce.planSubtitle': 'Günlük ve haftalık vardiya atamaları', 'workforce.addPlan': 'Plan Ekle', 'workforce.daily': 'Günlük', 'workforce.weekly': 'Haftalık', 'workforce.taskMissing': 'Görev belirtilmedi', 'workforce.machine': 'Makine {number}', 'workforce.noAssignment': 'Atama yok', 'workforce.employee': 'Personel', 'workforce.emptySlot': 'Boş', 'workforce.date': 'Tarih', 'workforce.shift': 'Vardiya', 'workforce.task': 'Görev', 'workforce.machineTitle': 'Makine', 'workforce.status': 'Durum', 'workforce.note': 'Not', 'workforce.unspecified': 'Belirtilmedi', 'workforce.edit': 'Düzenle', 'workforce.delete': 'Sil', 'workforce.noPlans': 'Bu dönem için çalışma planı bulunmuyor.', 'workforce.editPlan': 'Çalışma Planını Düzenle', 'workforce.newPlan': 'Yeni Çalışma Planı', 'workforce.machineNumber': 'Makine numarası', 'workforce.optional': 'Opsiyonel', 'workforce.saving': 'Kaydediliyor…',
    'workforce.task.MACHINE_OPERATOR': 'Makine Operatörü', 'workforce.task.PRODUCTION': 'Üretim', 'workforce.task.PACKAGING': 'Paketleme', 'workforce.task.WAREHOUSE': 'Depo', 'workforce.task.DELIVERY': 'Teslimat', 'workforce.task.ACCOUNTING': 'Muhasebe', 'workforce.task.GENERAL': 'Genel',
    'workforce.status.PLANNED': 'Planlandı', 'workforce.status.PRESENT': 'İşte', 'workforce.status.COMPLETED': 'Tamamlandı', 'workforce.status.ABSENT': 'Gelmedi', 'workforce.status.ON_LEAVE': 'İzinli', 'workforce.status.SICK_LEAVE': 'Raporlu', 'workforce.status.CANCELLED': 'İptal',
    'workforce.editEmployee': 'Düzenle', 'workforce.editEmployeeTitle': 'İşçiyi Düzenle', 'workforce.addEmployee': 'İşçi Ekle', 'workforce.removeEmployee': 'İşçiyi Çıkar', 'workforce.removeEmployeeConfirm': '{name} adlı işçi aktif kadrodan çıkarılacak. Geçmiş çalışma kayıtları korunacaktır. Onaylıyor musunuz?', 'workforce.employeeCreated': 'İşçi eklendi.', 'workforce.employeeUpdated': 'Çalışan güncellendi.', 'workforce.employeeRemoved': 'İşçi aktif kadrodan çıkarıldı.', 'workforce.employeeSaveError': 'İşçi kaydedilemedi.', 'workforce.editShift': 'Vardiyayı düzenle', 'workforce.shiftUpdated': 'Vardiya güncellendi.', 'workforce.cancelPlan': 'İptal', 'workforce.planCancelled': 'Plan iptal edildi.', 'workforce.shiftStart': 'Başlangıç', 'workforce.shiftEnd': 'Bitiş',
  },
  fr: {
    'workforce.loadError': 'Impossible de charger les employés.', 'workforce.planLoadError': 'Impossible de charger le planning.', 'workforce.planSaveError': 'Impossible d’enregistrer le planning.', 'workforce.tab.team': 'Personnel', 'workforce.tab.daily': 'Travail quotidien', 'workforce.tab.plan': 'Planning des équipes', 'workforce.tab.leave': 'Congés / Absences', 'workforce.tab.weekly': 'Planning hebdomadaire', 'workforce.total': 'Total personnel', 'workforce.active': 'Actifs', 'workforce.salaryTotal': 'Total mensuel des salaires', 'workforce.reviewCount': 'À examiner', 'workforce.title': 'Employés TRIKOMEX', 'workforce.report': 'Rapport du personnel', 'workforce.search': 'Rechercher un employé…', 'workforce.name': 'Nom', 'workforce.code': 'Code personnel', 'workforce.noCode': 'SANS CODE', 'workforce.salary': 'Salaire mensuel', 'workforce.shiftToday': 'Équipe du jour', 'workforce.statusToday': 'Statut du jour', 'workforce.reviewRequired': 'Examen requis', 'workforce.notPlanned': 'Non planifié', 'workforce.empty': 'Aucun employé.',
    'workforce.planTitle': 'Planning du personnel', 'workforce.planSubtitle': 'Affectations quotidiennes et hebdomadaires', 'workforce.addPlan': 'Ajouter un planning', 'workforce.daily': 'Quotidien', 'workforce.weekly': 'Hebdomadaire', 'workforce.taskMissing': 'Tâche non indiquée', 'workforce.machine': 'Machine {number}', 'workforce.noAssignment': 'Aucune affectation', 'workforce.employee': 'Employé', 'workforce.emptySlot': 'Vide', 'workforce.date': 'Date', 'workforce.shift': 'Équipe', 'workforce.task': 'Tâche', 'workforce.machineTitle': 'Machine', 'workforce.status': 'Statut', 'workforce.note': 'Note', 'workforce.unspecified': 'Non indiqué', 'workforce.edit': 'Modifier', 'workforce.delete': 'Supprimer', 'workforce.noPlans': 'Aucun planning pour cette période.', 'workforce.editPlan': 'Modifier le planning', 'workforce.newPlan': 'Nouveau planning', 'workforce.machineNumber': 'Numéro de machine', 'workforce.optional': 'Facultatif', 'workforce.saving': 'Enregistrement…',
    'workforce.task.MACHINE_OPERATOR': 'Opérateur machine', 'workforce.task.PRODUCTION': 'Production', 'workforce.task.PACKAGING': 'Emballage', 'workforce.task.WAREHOUSE': 'Entrepôt', 'workforce.task.DELIVERY': 'Livraison', 'workforce.task.ACCOUNTING': 'Comptabilité', 'workforce.task.GENERAL': 'Général',
    'workforce.status.PLANNED': 'Planifié', 'workforce.status.PRESENT': 'Présent', 'workforce.status.COMPLETED': 'Terminé', 'workforce.status.ABSENT': 'Absent', 'workforce.status.ON_LEAVE': 'En congé', 'workforce.status.SICK_LEAVE': 'Congé maladie', 'workforce.status.CANCELLED': 'Annulé',
    'workforce.editEmployee': 'Modifier', 'workforce.editEmployeeTitle': 'Modifier l’employé', 'workforce.addEmployee': 'Ajouter un employé', 'workforce.removeEmployee': 'Retirer l’employé', 'workforce.removeEmployeeConfirm': '{name} sera retiré du personnel actif. Son historique sera conservé. Confirmer ?', 'workforce.employeeCreated': 'Employé ajouté.', 'workforce.employeeUpdated': 'Employé mis à jour.', 'workforce.employeeRemoved': 'Employé retiré du personnel actif.', 'workforce.employeeSaveError': 'Impossible d’enregistrer l’employé.', 'workforce.editShift': 'Modifier l’équipe', 'workforce.shiftUpdated': 'Équipe mise à jour.', 'workforce.cancelPlan': 'Annuler', 'workforce.planCancelled': 'Planning annulé.', 'workforce.shiftStart': 'Début', 'workforce.shiftEnd': 'Fin',
  },
  en: {
    'workforce.loadError': 'Employees could not be loaded.', 'workforce.planLoadError': 'The work plan could not be loaded.', 'workforce.planSaveError': 'The plan could not be saved.', 'workforce.tab.team': 'Employees', 'workforce.tab.daily': 'Daily work', 'workforce.tab.plan': 'Shift plan', 'workforce.tab.leave': 'Leave / Absence', 'workforce.tab.weekly': 'Weekly plan', 'workforce.total': 'Total employees', 'workforce.active': 'Active', 'workforce.salaryTotal': 'Monthly salary total', 'workforce.reviewCount': 'Needs review', 'workforce.title': 'TRIKOMEX employees', 'workforce.report': 'Personnel report', 'workforce.search': 'Search employees…', 'workforce.name': 'Name', 'workforce.code': 'Employee code', 'workforce.noCode': 'NO CODE', 'workforce.salary': 'Monthly salary', 'workforce.shiftToday': 'Today’s shift', 'workforce.statusToday': 'Today’s status', 'workforce.reviewRequired': 'Review required', 'workforce.notPlanned': 'Not planned', 'workforce.empty': 'No employees found.',
    'workforce.planTitle': 'Employee work plan', 'workforce.planSubtitle': 'Daily and weekly shift assignments', 'workforce.addPlan': 'Add plan', 'workforce.daily': 'Daily', 'workforce.weekly': 'Weekly', 'workforce.taskMissing': 'Task not specified', 'workforce.machine': 'Machine {number}', 'workforce.noAssignment': 'No assignment', 'workforce.employee': 'Employee', 'workforce.emptySlot': 'Empty', 'workforce.date': 'Date', 'workforce.shift': 'Shift', 'workforce.task': 'Task', 'workforce.machineTitle': 'Machine', 'workforce.status': 'Status', 'workforce.note': 'Note', 'workforce.unspecified': 'Not specified', 'workforce.edit': 'Edit', 'workforce.delete': 'Delete', 'workforce.noPlans': 'No work plan for this period.', 'workforce.editPlan': 'Edit work plan', 'workforce.newPlan': 'New work plan', 'workforce.machineNumber': 'Machine number', 'workforce.optional': 'Optional', 'workforce.saving': 'Saving…',
    'workforce.task.MACHINE_OPERATOR': 'Machine operator', 'workforce.task.PRODUCTION': 'Production', 'workforce.task.PACKAGING': 'Packaging', 'workforce.task.WAREHOUSE': 'Warehouse', 'workforce.task.DELIVERY': 'Delivery', 'workforce.task.ACCOUNTING': 'Accounting', 'workforce.task.GENERAL': 'General',
    'workforce.status.PLANNED': 'Planned', 'workforce.status.PRESENT': 'Present', 'workforce.status.COMPLETED': 'Completed', 'workforce.status.ABSENT': 'Absent', 'workforce.status.ON_LEAVE': 'On leave', 'workforce.status.SICK_LEAVE': 'Sick leave', 'workforce.status.CANCELLED': 'Cancelled',
    'workforce.editEmployee': 'Edit', 'workforce.editEmployeeTitle': 'Edit employee', 'workforce.addEmployee': 'Add employee', 'workforce.removeEmployee': 'Remove employee', 'workforce.removeEmployeeConfirm': '{name} will be removed from active staff. Work history will be preserved. Continue?', 'workforce.employeeCreated': 'Employee added.', 'workforce.employeeUpdated': 'Employee updated.', 'workforce.employeeRemoved': 'Employee removed from active staff.', 'workforce.employeeSaveError': 'Employee could not be saved.', 'workforce.editShift': 'Edit shift', 'workforce.shiftUpdated': 'Shift updated.', 'workforce.cancelPlan': 'Cancel', 'workforce.planCancelled': 'Plan cancelled.', 'workforce.shiftStart': 'Start', 'workforce.shiftEnd': 'End',
  },
} as const
